// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz2wJESp2Fl9tItXZtH38pBecrqZahSPo',
    appId: '1:891916832609:android:e88cb0c7c1cefd51337f20',
    messagingSenderId: '891916832609',
    projectId: 'geoforestsurveillance',
    storageBucket: 'geoforestsurveillance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKoKb69T1hvPh-4H8TEKrYsgpRGqWLiEk',
    appId: '1:891916832609:ios:8002863cced76269337f20',
    messagingSenderId: '891916832609',
    projectId: 'geoforestsurveillance',
    storageBucket: 'geoforestsurveillance.firebasestorage.app',
    iosBundleId: 'com.example.geoForestSurveillance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKoKb69T1hvPh-4H8TEKrYsgpRGqWLiEk',
    appId: '1:891916832609:ios:8002863cced76269337f20',
    messagingSenderId: '891916832609',
    projectId: 'geoforestsurveillance',
    storageBucket: 'geoforestsurveillance.firebasestorage.app',
    iosBundleId: 'com.example.geoForestSurveillance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf9B4XHL76xeKzW45oT9FpzWbtCM7yaso',
    appId: '1:891916832609:web:d6c18d577076e9e2337f20',
    messagingSenderId: '891916832609',
    projectId: 'geoforestsurveillance',
    authDomain: 'geoforestsurveillance.firebaseapp.com',
    storageBucket: 'geoforestsurveillance.firebasestorage.app',
    measurementId: 'G-TTHC08Z2YW',
  );

}