// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA39yFmfxz-pW_973QyokN8qOMNviKWh70',
    appId: '1:946133765243:android:8a7d719d0875e8bf1766de',
    messagingSenderId: '946133765243',
    projectId: 'vigilancia-dengue',
    storageBucket: 'vigilancia-dengue.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPHgtSwHiZgQExj5VOD-T8K2HUEUJNARQ',
    appId: '1:946133765243:ios:569d103f873441861766de',
    messagingSenderId: '946133765243',
    projectId: 'vigilancia-dengue',
    storageBucket: 'vigilancia-dengue.firebasestorage.app',
    iosBundleId: 'com.example.geoForestSurveillance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPHgtSwHiZgQExj5VOD-T8K2HUEUJNARQ',
    appId: '1:946133765243:ios:569d103f873441861766de',
    messagingSenderId: '946133765243',
    projectId: 'vigilancia-dengue',
    storageBucket: 'vigilancia-dengue.firebasestorage.app',
    iosBundleId: 'com.example.geoForestSurveillance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBstyU3X2WErNNJmyGBK09yRfraMZwOrQ4',
    appId: '1:946133765243:web:b8ed11403979b9e01766de',
    messagingSenderId: '946133765243',
    projectId: 'vigilancia-dengue',
    authDomain: 'vigilancia-dengue.firebaseapp.com',
    storageBucket: 'vigilancia-dengue.firebasestorage.app',
    measurementId: 'G-NQYNF6NZMX',
  );
}
